package:
  name: conda-manager
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../
  git_tag: {% if environ.get('PRERELEASE') == 'True' %} master {% else %} {{ environ.get('GIT_DESCRIBE_TAG') }} {% endif %}

build:
  noarch_python: True
  number: {% if environ.get('PRERELEASE') == 'True' %} {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }} {% else %} 0 {% endif %}

requirements:
  build:
    - python
    - setuptools
  run:
    - anaconda-client
    - python
    - pyyaml
    - qtawesome
    - qtpy
    - requests
test:
  imports:
    - conda_manager

  requires:
    - anaconda-client
    - python
    - pyyaml
    - qtawesome
    - qtpy
    - requests
    - qt
    - pyqt

about:
  home: https://github.com/spyder-ide/conda-manager
  license: MIT
  summary: Graphical conda package manager with Spyder plugin integration
