package:
  name: conda-manager
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

source:
  git_url: ../
  git_tag: {{ environ.get('GIT_DESCRIBE_TAG') }}

build:
  noarch_python: True

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - qtpy
    - conda_manager

  requires:
    - pyqt
    - qtpy

about:
  home: https://github.com/spyder-ide/conda-manager
  license: MIT
  summary: Graphical conda package manager with Spyder plugin integration
